name: Test Project
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        # Usar uma ação para fazer checkout do código fonte
        uses: actions/checkout@v3
      - name: Install NodeJS
        # Usar uma ação para configurar o Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install Dependencies
        run: npm ci
      - name: Run Tests
        run: npm test
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        # Usar uma ação para fazer checkout do código fonte
        uses: actions/checkout@v3
      - name: Install NodeJS
        # Usar uma ação para configurar o Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install Dependencies
        run: npm ci
      - name: BUild Project
        run: npm run build
      - name: Deploy
        run: echo "Deploying..."
